version: '{build}-{branch}'
image: Visual Studio 2017

clone_depth: 1

init:
- ps: |
    function craft() {
        & C:\python36\python.exe "C:\CraftMaster\CraftMaster\CraftMaster.py" --config "$env:APPVEYOR_BUILD_FOLDER\appveyor.ini" --variables "APPVEYOR_BUILD_FOLDER=$env:APPVEYOR_BUILD_FOLDER" --target $env:TARGET -c $args
        if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
    }
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- ps: |
    #use cmd to silence powershell behaviour for stderr
    & cmd /C "git clone -q --depth=1 git://anongit.kde.org/craftmaster.git C:\CraftMaster\CraftMaster 2>&1"
    & cmd /C "git clone git://anongit.freedesktop.org/poppler/test $env:APPVEYOR_BUILD_FOLDER/../test 2>&1"
    craft craft
    craft --install-deps poppler

build_script:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER poppler

after_build:
- ps: |
    craft --no-cache --src-dir $env:APPVEYOR_BUILD_FOLDER --package poppler

test_script:
- ps: |
   craft --src-dir $env:APPVEYOR_BUILD_FOLDER --test poppler
   & cmd /C "copy C:\CraftMaster\windows-mingw_64-gcc\tmp\poppler-master-*-master-windows-mingw_64-gcc.7z C:\projects\poppler-mirror\"
   & cmd /C "xcopy C:\CraftMaster\windows-mingw_64-gcc\build\qt-libs\poppler\image-Release-master C:\projects\poppler-mirror\build_result"


environment:
    matrix:
    - TARGET: windows-mingw_64-gcc
#    - TARGET: windows-msvc2017_64-cl
    APPVEYOR_RDP_PASSWORD: Thuk3zee

artifacts:
  - path: poppler-master-*-master-windows-mingw_64-gcc.7z
    name: poppler-libs

  - path: build_result
    name: build-result
    